name: "my workflow"

on: ['push', 'pull_request', 'workflow_dispatch']

jobs:
  my-job:
    runs-on: ubuntu-latest

    env:
      URL: ${{ secrets.SERVICENOW_URL }}
      USER_NAME: ${{ secrets.SERVICENOW_USERNAME }}
      PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}
      CI: "true"
      
    steps:
      - name: "Download Repo"
        run: echo "Hello workflow action triggered"
      - name: "Checkout the code"
        uses: actions/checkout@v4
      - name: "Installing Node"
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: "Run playwright test"
        run: npm run test:qa
      - name: "Upload Playwright Report"
        uses: actions/upload-artifact@v4
        with:
          name: Execution-report
          path: playwright-report

