name: "my workflow"

on: ['push', 'pull_request', 'workflow_dispatch']

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Download Repo"
        run: echo "Hello"
      - name: "Checkout the code"
        uses: actions/checkout@v4
      
